### ISSUE TITLE
Broken link to "A Datalog Model of Must-Alias Analysis"

### ISSUE THREAD

**Issue by efferifick** [gbalats/gbalats.github.io#6]
Hello,

Just letting you know about a broken link on your website. [This link](https://github.com/gbalats/gbalats.github.io/blob/master/_data/publications.yaml#L97) gives me an error 404 not found. I found a [copy of the paper on one of the co-authors website](https://yanniss.github.io/must-alias-soap17.pdf).

**Comment by gbalats** [comment]
Thanks for letting me know! Fixed.
